robot:
  port: COM6
  baudrate: 115200
  home_position:
    x: 200.0
    y: 0.0
    z: 50.0
    r: 0.0
  sorting_bins:
    nut:
      x: 196.0
      y: -168.0
      z: 37.0
      r: 0.0
    long_bolt:
      x: 41.0
      y: -256.0
      z: 33.0
      r: 0.0
    short_bolt:
      x: 132.0
      y: -223.0
      z: 31.0
      r: 0.0
  pickup_zone:
    x: 150.0
    y: 0.0
    z_safe: 80.0
    z_bin: 10.0
  workspace:
    x_min: 100.0
    x_max: 320.0
    y_min: -150.0
    y_max: 150.0
    z_min: 0.0
    z_max: 100.0
  speed: 80
  acceleration: 80
  gripper:
    close_value: 480
    open_value: 200
    close_delay: 0.5
    open_delay: 0.3
